import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from './api';
import Login from './Login';
import type { Comment, Project, Ticket, User } from './types';

const statuses = ['TO_DO', 'IN_PROGRESS', 'NEED_INFORMATION', 'READY_FOR_UAT', 'READY_FOR_PROD', 'DEPLOYED', 'DONE', 'ON_HOLD', 'BACKLOG'];
const priorities = ['HIGHEST', 'HIGH', 'MEDIUM', 'LOW', 'LOWEST'];
const blankTicket = { title: '', description: '', priority: 'MEDIUM', status: 'TO_DO', projectId: '', assignedToId: '' };
type TicketForm = typeof blankTicket;

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('flowbit_token') || '');
  const [user, setUser] = useState<User | null>(() => JSON.parse(localStorage.getItem('flowbit_user') || 'null'));
  const [page, setPage] = useState('Dashboard');
  const [tickets, setTickets] = useState<Ticket[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [total, setTotal] = useState(0); const [skip, setSkip] = useState(0); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [projectId, setProjectId] = useState('');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [ticketForm, setTicketForm] = useState<TicketForm>(blankTicket); const [editing, setEditing] = useState<Ticket | null>(null); const [detail, setDetail] = useState<Ticket | null>(null);
  const limit = 10;
  const query = useMemo(() => new URLSearchParams({ limit: String(limit), skip: String(skip), ...(search && { searchString: search }), ...(status && { status }), ...(priority && { priority }), ...(projectId && { projectId }) }).toString(), [skip, search, status, priority, projectId]);

  async function loadTickets() { if (!token) return; setLoading(true); try { const data = await api(`/tickets?${query}`, token); setTickets(data.tickets || []); setTotal(data.totalCount || 0); } catch (e) { setError(message(e)); } finally { setLoading(false); } }
  async function loadSupport() { if (!token) return; try { const [p, u] = await Promise.all([api('/projects?limit=100', token), api('/users?limit=100', token)]); setProjects(p.projects || []); setUsers(u.users || []); } catch (e) { setError(message(e)); } }
  useEffect(() => { loadTickets(); }, [token, query]);
  useEffect(() => { loadSupport(); }, [token]);
  function login(nextToken: string, nextUser: User) { localStorage.setItem('flowbit_token', nextToken); localStorage.setItem('flowbit_user', JSON.stringify(nextUser)); setToken(nextToken); setUser(nextUser); }
  function logout() { localStorage.removeItem('flowbit_token'); localStorage.removeItem('flowbit_user'); setToken(''); setUser(null); }
  function resetFilters() { setSearch(''); setStatus(''); setPriority(''); setProjectId(''); setSkip(0); }
  async function saveTicket(event: FormEvent) { event.preventDefault(); try { const path = editing ? `/tickets/${editing.id}` : '/tickets'; await api(path, token, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(ticketForm) }); setEditing(null); setTicketForm(blankTicket); await loadTickets(); } catch (e) { setError(message(e)); } }
  async function removeTicket(ticket: Ticket) { if (!window.confirm(`Delete ${ticket.ticketNumber}?`)) return; try { await api(`/tickets/${ticket.id}`, token, { method: 'DELETE' }); if (detail?.id === ticket.id) setDetail(null); await loadTickets(); } catch (e) { setError(message(e)); } }
  async function openDetail(ticket: Ticket) { try { setDetail(await api(`/tickets/${ticket.id}`, token)); } catch (e) { setError(message(e)); } }
  function editTicket(ticket: Ticket) { setEditing(ticket); setTicketForm({ title: ticket.title, description: ticket.description, status: ticket.status, priority: ticket.priority, projectId: ticket.project.id, assignedToId: ticket.assignee.id }); }
  if (!token || !user) return <Login onLogin={login} />;
  const resolved = tickets.filter(t => t.status === 'DONE').length; const open = total - resolved;
  return <div className="app-shell"><aside className="sidebar"><div className="brand">flow<span>bit</span></div><p className="workspace-label">TICKET WORKSPACE</p>{['Dashboard', 'Tickets', 'Projects', 'Users'].map(item => <button key={item} className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => setPage(item)}>{item}</button>)}<div className="sidebar-bottom"><strong>{user.name}</strong><small>{roleName(user.role)}</small><button className="logout" onClick={logout}>Sign out</button></div></aside><main className="content"><header><div><p className="eyebrow">WORKSPACE</p><h1>{page}</h1></div>{page === 'Tickets' && <button onClick={() => { setEditing(null); setTicketForm({ ...blankTicket, projectId: projects[0]?.id || '', assignedToId: users[0]?.id || '' }); }}>+ New ticket</button>}</header>{error && <p className="error banner">{error}<button className="text-button" onClick={() => setError('')}>Dismiss</button></p>}
    {page === 'Dashboard' && <Dashboard total={total} open={open} resolved={resolved} tickets={tickets} onTicket={openDetail} />}
    {page === 'Tickets' && <><Filters search={search} status={status} priority={priority} projectId={projectId} projects={projects} onSearch={v => { setSearch(v); setSkip(0); }} onStatus={v => { setStatus(v); setSkip(0); }} onPriority={v => { setPriority(v); setSkip(0); }} onProject={v => { setProjectId(v); setSkip(0); }} onReset={resetFilters} /><TicketTable tickets={tickets} loading={loading} onDetail={openDetail} onEdit={editTicket} onDelete={removeTicket} /><Pagination total={total} skip={skip} limit={limit} onPage={setSkip} /></>}
    {page === 'Projects' && <ProjectsPage projects={projects} token={token} onChange={loadSupport} onError={setError} />}
    {page === 'Users' && <UsersPage users={users} projects={projects} token={token} onChange={loadSupport} onError={setError} />}
  </main>{(editing || (!editing && ticketForm.projectId)) && page === 'Tickets' && <TicketForm form={ticketForm} projects={projects} users={users} editing={editing} onChange={setTicketForm} onClose={() => { setEditing(null); setTicketForm(blankTicket); }} onSubmit={saveTicket} />}{detail && <TicketDetail ticket={detail} currentUser={user} token={token} onClose={() => setDetail(null)} onRefresh={openDetail} onEdit={() => { setDetail(null); editTicket(detail); }} onDelete={() => removeTicket(detail)} onError={setError} />}</div>;
}

function Dashboard({ total, open, resolved, tickets, onTicket }: { total: number; open: number; resolved: number; tickets: Ticket[]; onTicket: (t: Ticket) => void }) { return <><section className="stats"><Stat label="All tickets" value={total} /><Stat label="Open tickets" value={open} /><Stat label="Resolved" value={resolved} /></section><section className="panel"><div className="section-heading"><div><h2>Recent tickets</h2><p>Track the latest work across your workspace.</p></div></div><div className="recent-list">{tickets.slice(0, 5).map(t => <button className="recent-row" key={t.id} onClick={() => onTicket(t)}><span><strong>{t.ticketNumber}</strong> {t.title}</span><Badge value={t.status} /></button>)}{!tickets.length && <Empty text="No tickets yet. Create the first ticket to start tracking work." />}</div></section></>; }
function Stat({ label, value }: { label: string; value: number }) { return <article className="stat"><p>{label}</p><strong>{value}</strong></article>; }
function Filters(props: { search: string; status: string; priority: string; projectId: string; projects: Project[]; onSearch: (v: string) => void; onStatus: (v: string) => void; onPriority: (v: string) => void; onProject: (v: string) => void; onReset: () => void }) { return <section className="filters panel"><input aria-label="Search tickets" placeholder="Search title, description, or ticket number" value={props.search} onChange={e => props.onSearch(e.target.value)} /><select value={props.status} onChange={e => props.onStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(v => <option key={v}>{label(v)}</option>)}</select><select value={props.priority} onChange={e => props.onPriority(e.target.value)}><option value="">All priorities</option>{priorities.map(v => <option key={v}>{label(v)}</option>)}</select><select value={props.projectId} onChange={e => props.onProject(e.target.value)}><option value="">All projects</option>{props.projects.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="secondary" onClick={props.onReset}>Reset</button></section>; }
function TicketTable({ tickets, loading, onDetail, onEdit, onDelete }: { tickets: Ticket[]; loading: boolean; onDetail: (t: Ticket) => void; onEdit: (t: Ticket) => void; onDelete: (t: Ticket) => void }) { return <section className="panel table-wrap"><table><thead><tr><th>Ticket</th><th>Status</th><th>Priority</th><th>Project</th><th>Assignee</th><th aria-label="Actions" /></tr></thead><tbody>{tickets.map(t => <tr key={t.id}><td><button className="table-link" onClick={() => onDetail(t)}><strong>{t.ticketNumber}</strong><span>{t.title}</span></button></td><td><Badge value={t.status} /></td><td><Badge value={t.priority} /></td><td>{t.project?.name}</td><td>{t.assignee?.name}</td><td className="row-actions"><button className="secondary small" onClick={() => onEdit(t)}>Edit</button><button className="danger small" onClick={() => onDelete(t)}>Delete</button></td></tr>)}{!tickets.length && <tr><td colSpan={6}><Empty text={loading ? 'Loading tickets…' : 'No tickets match these filters.'} /></td></tr>}</tbody></table></section>; }
function Pagination({ total, skip, limit, onPage }: { total: number; skip: number; limit: number; onPage: (skip: number) => void }) { const page = Math.floor(skip / limit) + 1; const pages = Math.max(1, Math.ceil(total / limit)); return <div className="pagination"><span>{total ? `${skip + 1}-${Math.min(skip + limit, total)} of ${total}` : '0 tickets'}</span><button className="secondary small" disabled={page === 1} onClick={() => onPage(skip - limit)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary small" disabled={page === pages} onClick={() => onPage(skip + limit)}>Next</button></div>; }
function TicketForm({ form, projects, users, editing, onChange, onClose, onSubmit }: { form: TicketForm; projects: Project[]; users: User[]; editing: Ticket | null; onChange: (form: TicketForm) => void; onClose: () => void; onSubmit: (e: FormEvent) => void }) { return <Modal title={editing ? `Edit ${editing.ticketNumber}` : 'New ticket'} onClose={onClose}><form className="form" onSubmit={onSubmit}><label>Title<input required maxLength={140} value={form.title} onChange={e => onChange({ ...form, title: e.target.value })} /></label><label>Description<textarea required value={form.description} onChange={e => onChange({ ...form, description: e.target.value })} /></label><div className="form-grid"><Select label="Priority" value={form.priority} values={priorities} onChange={v => onChange({ ...form, priority: v })} /><Select label="Status" value={form.status} values={statuses} onChange={v => onChange({ ...form, status: v })} /></div><label>Project<select required value={form.projectId} onChange={e => onChange({ ...form, projectId: e.target.value })}><option value="">Select a project</option>{projects.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Assignee<select required value={form.assignedToId} onChange={e => onChange({ ...form, assignedToId: e.target.value })}><option value="">Select an assignee</option>{users.map(u => <option value={u.id} key={u.id}>{u.name}</option>)}</select></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button>{editing ? 'Save changes' : 'Create ticket'}</button></div></form></Modal>; }
function TicketDetail({ ticket, currentUser, token, onClose, onRefresh, onEdit, onDelete, onError }: { ticket: Ticket & { comments?: Comment[] }; currentUser: User; token: string; onClose: () => void; onRefresh: (t: Ticket) => void; onEdit: () => void; onDelete: () => void; onError: (v: string) => void }) { const [body, setBody] = useState(''); const [saving, setSaving] = useState(false); async function addComment(e: FormEvent) { e.preventDefault(); if (!body.trim()) return; setSaving(true); try { await api(`/tickets/${ticket.id}/comments`, token, { method: 'POST', body: JSON.stringify({ description: body }) }); setBody(''); await onRefresh(ticket); } catch (e) { onError(message(e)); } finally { setSaving(false); } } async function deleteComment(comment: Comment) { if (!window.confirm('Delete this comment?')) return; try { await api(`/tickets/${ticket.id}/comments/${comment.id}`, token, { method: 'DELETE' }); await onRefresh(ticket); } catch (e) { onError(message(e)); } } return <Modal title={ticket.ticketNumber} onClose={onClose} wide><div className="detail-head"><div><h3>{ticket.title}</h3><p className="muted">{ticket.project.name} · Assigned to {ticket.assignee.name}</p></div><div className="row-actions"><button className="secondary small" onClick={onEdit}>Edit</button><button className="danger small" onClick={onDelete}>Delete</button></div></div><div className="badges"><Badge value={ticket.status} /><Badge value={ticket.priority} /></div><p className="description">{ticket.description}</p><section className="comments"><h3>Comments ({ticket.comments?.length || 0})</h3><form className="comment-form" onSubmit={addComment}><textarea value={body} maxLength={2000} placeholder="Add a comment…" onChange={e => setBody(e.target.value)} /><button disabled={saving}>{saving ? 'Posting…' : 'Post comment'}</button></form>{ticket.comments?.map(c => <article className="comment" key={c.id}><div><strong>{c.author?.name || 'Team member'}</strong><span>{formatDate(c.createdAt)}</span></div><p>{c.description}</p>{(c.author?.id === currentUser.id || roleName(currentUser.role) === 'ADMIN') && <button className="text-button danger-text" onClick={() => deleteComment(c)}>Delete</button>}</article>)}{!ticket.comments?.length && <Empty text="No comments yet." />}</section></Modal>; }
function ProjectsPage({ projects, token, onChange, onError }: { projects: Project[]; token: string; onChange: () => Promise<void>; onError: (v: string) => void }) { const [name, setName] = useState(''); const [description, setDescription] = useState(''); async function add(e: FormEvent) { e.preventDefault(); try { await api('/projects', token, { method: 'POST', body: JSON.stringify({ name, description }) }); setName(''); setDescription(''); await onChange(); } catch (e) { onError(message(e)); } } return <div className="split-page"><section className="cards">{projects.map(p => <article className="panel" key={p.id}><h2>{p.name}</h2><p>{p.description || 'No description yet.'}</p></article>)}{!projects.length && <Empty text="No active projects." />}</section><section className="panel"><h2>Create project</h2><form className="form" onSubmit={add}><label>Name<input required value={name} onChange={e => setName(e.target.value)} /></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} /></label><button>Create project</button></form></section></div>; }
function UsersPage({ users, projects, token, onChange, onError }: { users: User[]; projects: Project[]; token: string; onChange: () => Promise<void>; onError: (v: string) => void }) { const [form, setForm] = useState({ name: '', email: '', password: '', projectId: projects[0]?.id || '', roleId: '' }); const [roles, setRoles] = useState<{ id: string; title: string }[]>([]); useEffect(() => { api('/roles?limit=100', token).then(r => { setRoles(r.roles || []); setForm(f => ({ ...f, roleId: r.roles?.[0]?.id || '' })); }).catch(e => onError(message(e))); }, [token]); async function add(e: FormEvent) { e.preventDefault(); try { await api('/users', token, { method: 'POST', body: JSON.stringify(form) }); setForm({ name: '', email: '', password: '', projectId: projects[0]?.id || '', roleId: roles[0]?.id || '' }); await onChange(); } catch (e) { onError(message(e)); } } return <div className="split-page"><section className="panel table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Project</th></tr></thead><tbody>{users.map(u => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><Badge value={roleName(u.role)} /></td><td>{projectName(u.project)}</td></tr>)}</tbody></table></section><section className="panel"><h2>Add user</h2><form className="form" onSubmit={add}><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Temporary password<input required minLength={6} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><label>Role<select required value={form.roleId} onChange={e => setForm({ ...form, roleId: e.target.value })}>{roles.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Project<select required value={form.projectId} onChange={e => setForm({ ...form, projectId: e.target.value })}>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button>Add user</button></form></section></div>; }
function Modal({ title, children, onClose, wide = false }: { title: string; children: React.ReactNode; onClose: () => void; wide?: boolean }) { return <div className="modal-backdrop" role="presentation"><section className={`modal ${wide ? 'modal-wide' : ''}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Close" onClick={onClose}>×</button></div>{children}</section></div>; }
function Select({ label: text, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (v: string) => void }) { return <label>{text}<select value={value} onChange={e => onChange(e.target.value)}>{values.map(v => <option value={v} key={v}>{label(v)}</option>)}</select></label>; }
function Badge({ value }: { value: string }) { return <span className={`badge badge-${value.toLowerCase()}`}>{label(value)}</span>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function label(value: string) { return value.split('_').join(' '); } function roleName(role: User['role']) { return typeof role === 'string' ? role : role.title; } function projectName(project: User['project']) { return typeof project === 'string' ? project : project.name; } function formatDate(value: string) { return new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }); } function message(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong.'; }
